### ISSUE TITLE
 Code doesn't run

### ISSUE THREAD

**Issue by pkeppeler** [Colter13/hello-world#3]
Hello, I am trying to use this on a Samsung Galaxy S21, but I can't figure out how to run it. It seems to not work. Can you plz fix???
![20240610_143628](https://github.com/Colter13/hello-world/assets/14352490/b5ac0945-e57f-4537-9269-513490a1fd86)

**Comment by Colter13** [comment]
My advice would be to try and run it in a IDE rather than a text editor.
